services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3307:3306"   # Porta do host 3307 -> Porta do container 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
